### ISSUE TITLE
Github login is not working

### ISSUE THREAD

**Issue by jonathanalvares9009** [CSwala/CSwala-android#30] opened 2021-03-08 16:34 UTC
Sir, I would like to work on this issue

**Comment by riturajjain2000** [comment] 2021-03-09 07:11
I can assign max. 2 issues to a participant at a time, plz fix other issues to get this assigned to you!

**Comment by adiig7** [comment] 2021-03-09 12:55
Can i work on this issue?

**Comment by jonathanalvares9009** [comment] 2021-03-09 13:35
I'm working on this issue

**Comment by adiig7** [comment] 2021-03-10 13:45
@jonathanalvares9009 Have you done it? If not can i take up this one?

**Comment by fin1te** [comment] 2021-03-10 14:48
Let me know when this issue is resolved, thanks!

**Comment by adiig7** [comment] 2021-03-11 04:47
@riturajjain2000 it is been 2 days and the issue hasn't been resolved yet and there isn't any update from @jonathanalvares9009 too. Can i complete this issue?

**Comment by riturajjain2000** [comment] 2021-03-11 07:44
Wait for 1 more day , If he is still unable to make a PR then I'll reassign it!

**Comment by jonathanalvares9009** [comment] 2021-03-11 08:50
@riturajjain2000 I have tried for the past two days to implement github authorisation but I'm unable solved it deosn't work completely. You can assign it to @adiig7 I also want to learn how to implement github.

**Comment by adiig7** [comment] 2021-03-11 08:53
@riturajjain2000 please assign it to me.

**Comment by jonathanalvares9009** [comment] 2021-03-11 08:57
@adiig7 just start implementing it

**Comment by riturajjain2000** [comment] 2021-03-11 09:09
> @riturajjain2000 I have tried for the past two days to implement github authorisation but I'm unable solved it deosn't work completely. You can assign it to @adiig7 I also want to learn how to implement github.

ok

**Comment by fin1te** [comment] 2021-03-11 11:19
Let me try next if the issue is not resolved, Thanks!

**Comment by riturajjain2000** [comment] 2021-03-11 13:14
sure

**Comment by adiig7** [comment] 2021-03-11 15:37
@fin1te I'm already on to it.

**Comment by fin1te** [comment] 2021-03-15 12:47
@adiig7 any updates?

**Comment by fin1te** [comment] 2021-03-19 18:17
@riturajjain2000  if it is not yet done, can I try this?

**Comment by deepsjuneja** [comment] 2021-04-16 14:21
Can I work on this issue?

**Comment by deepsjuneja** [comment] 2021-04-17 07:04
> Can I work on this issue?

@riturajjain2000 you haven't assigned me the issue yet.

**Comment by riturajjain2000** [comment] 2021-04-17 07:07
done

**Closed** 2021-05-23 13:58 UTC
Labels: Level2, bug, gssoc21
